### ISSUE TITLE
nemo 2.8.6.r20.gf539ba5-1

### ISSUE THREAD

**Issue by Electro-magnetics** [manjaro/packages-community#130]
Hello,

The latest version of nemo here, 2.8.6.r20.gf539ba5-1, breaks the "--no-desktop" functionality of nemo. Rolling back to just 2.8.6 (which is the latest version in the regular arch repositories)  has worked fine. I am using manjaro-xfce and this issue affects all my systems.

I noticed someone else reporting this same issue under https://github.com/linuxmint/nemo/issues/1097 and they were asked to report it here but they did not, hence I am.

Thanks

**Comment by oberon2007** [comment]
I see, thank you. The 2.8.6 package had some major bugs in Cinnamon and we switched to the git-version for that reason. Since **nemo** is the default browser for Cinnamon this looks to be the priority with this package. 
I see that 2.8.7 has meanwhile been released. So I am happy to switch to this one now.

**Comment by oberon2007** [comment]
https://github.com/manjaro/packages-community/commit/8abaaa75c23868b41a345323659a7a9d37eb2afd
