### ISSUE TITLE
[package request] otter-browser and qt5-webkit-ng-weekly

### ISSUE THREAD

**Issue by m4sk1n** [manjaro/packages-community#285]
It would be nice to have package for [Otter Browser](https://GitHub.com/otterbrowser/otter-browser). It's modern Qt5-based browser inspired by classic Opera 12.x UI. Now (in my honest opinion) there is no other good browser for KDE desktops (this browser can use Breeze theme and icons). Before release of 'stable' version package should contain 'otter-browser-weekly' (AUR package maintained by me).
Also, because it uses qt5-webkit, (qt5-webengine is also supported, but it is missing some features) there should be package called for example 'qt5-webkit-ng-weekly' which would be built from (upstream) [this repo](http://GitHub.com/annulen/webkit). Stable versions are released once a few months, so it would be nice to have something like this.
sorry for my bad English

**Comment by Ste74** [comment]
Thank you for your effort .. but if none of the maintainers want to use in our isos editions this will not be included this is rule in manjaro .

**Comment by m4sk1n** [comment]
@Ste74, I see that not every package (that's not on Arch community repo) is included on any ISO edition

**Comment by Ste74** [comment]
Yes this is our overlay pkgs for Manjaro : not all pkgs in Manjaro comes from Arch official repository . We are a little team to build or maintain a lot of pkgs . Only if a maintainer want use a extra pkg this can be added on our repo . Otter browser is only another browser so why we have to add if is present on AUR ( user can easly install from AUR ) .. I don't know if @excalibur1234 or @Kirek want use for lxqt or plasma edition because we have already firefox-kde pkg ...

**Comment by excalibur1234** [comment]
the lxqt edition uses qupzilla, because it is based on qt-webengine. qt-webengine is a part of qt5 and considered secure (but sometimes a little outdated).
otter-browser - as you have already mentioned - still uses qt-webkit. despite qt-webkit being maintained again by volunteers, i do not consider it secure.
i have tested otter-browser with qt-webengine, but it kept crashing. this was a reason i switched to qupzilla. the other reason was, because qupzilla is already in the community packages.

i have had otter-browser installed from the AUR for about a year. it worked very well. if you prefer otter-browser, i recommend to install it from AUR.
