### ISSUE TITLE
packnroll ?

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-community#327]
I was just looking through packages depending on qt5 to find what might still need rebulding.
There I stumbled again over **packnroll**... I'm not sure why we have this in the repos - in any case the source appears to be unmaintained since more than two years.
Do we still want to keep this? Rebuild it?
@philmmanjaro I have a dim memory that you adopted the package originally for some reason?

**Comment by philmmanjaro** [comment]
I already rebuilt it. Maybe we should check that package once more and why we have it. I simply don't remember :smile:

**Comment by oberon2007** [comment]
https://github.com/manjaro/packages-community/issues/22

**Comment by Ste74** [comment]
Funny is a gui interface to build and manage pkgbuild/pkgs

**Comment by oberon2007** [comment]
So is it needed?

**Comment by Huluti** [comment]
any news?

**Comment by Ste74** [comment]
Honestly i have try it and this gui to build the pkgs is not usefull for us. What i mean is this : with this GUI we can open a `PKGBUILD` and modify or create it, we can update the `checksums` and sure we can create a tarball but only if the pkg have already the depends installed in our system. For our packaging is not usefull because not build in a clean chroot, seem only a gui for `makepkg`.

**Comment by Huluti** [comment]
I see. So, if it isn't in arch and that we don't use it to develop Manjaro, it has nothing to do in our repos, that's the rule?

**Comment by Ste74** [comment]
closed via
https://github.com/manjaro/packages-community/commit/43fe269b9f8aeeebc48be497af6d4bd0a156e804
