### ISSUE TITLE
[manjaro-aur-support] don't nag on live-session

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/packages-community#364]
@oberon2007: it makes totally no sense to nag the user in live-session about AUR support detected.

**Comment by oberon2007** [comment]
i agree. i didn't introduce that, just adjusted the icon and formatting ;)
@Ste74 ideas?

**Comment by oberon2007** [comment]
we could just include a switch to not trigger in live session

**Comment by Ste74** [comment]
Maybe m-a-s work only if pacaur or yaourt is found in the system .. this is installed ?

**Comment by oberon2007** [comment]
It does work! But why would it be needed in live environment?

**Comment by Ste74** [comment]
In mate,budgie and gnome i not install aur wrapper so is only a silent pkg also in live .. if you want disable it in live-overlay add the .desktop file and disable it .. in this way the check is disable and not show anything.. 
Only if you do it in the system installed after 5 min the notification appear because in any case the wrapper is installed...

**Comment by oberon2007** [comment]
https://github.com/manjaro/packages-community/commit/7feabf1776e2eeec5342f83aef0321261f79f454

**Comment by oberon2007** [comment]
I've included a switch to only run in an installed system. Also simplified the script a little. Hope you agree, @Ste74 :)

**Comment by Ste74** [comment]
Of course , more clean :D thank you ;)
