### ISSUE TITLE
[Question] Why did you remove default - pamac choice in Gnome-shell-extension-manjaro-update?

### ISSUE THREAD

**Issue by ceyhunnabiyev** [manjaro/packages-community#425]

**Comment by Ste74** [comment]
Let me see.. seem my post install script not work now..

**Comment by ceyhunnabiyev** [comment]
@Ste74 , please fix this issue, because I love this extension, especially showing package list for update, and  it would be nice to add new version package to Stable Branch directly.

Thanks for this Great Extension.

**Comment by Ste74** [comment]
@ceyhunnabiyev please try v3.2 . Pushed in all branch just now

**Comment by ceyhunnabiyev** [comment]
Now extension doesn't work:
![screenshot from 2017-12-17 21-12-23](https://user-images.githubusercontent.com/5506156/34081938-2847f8ba-e36f-11e7-98a5-4afaf892ff82.png)

**Comment by Ste74** [comment]
I have a little problem with my gnome box .. sorry if delay the answer .. 
try to remove 
`sudo rm /usr/share/gnome-shell/extensions/manjaro-update@Chrysostomus/schemas/gschemas.compiled`
and recompile the schemas
`sudo glib-compile-schemas $pkgdir/usr/share/gnome-shell/extensions/manjaro-update@Chrysostomus/schemas/`

post error if appear otherwise try if now default settings are showed

**Comment by ceyhunnabiyev** [comment]
@Ste74 , Thank you..
`/usr/share/gnome-shell/extensions/manjaro-update@Chrysostomus/schemas/gschemas.compiled` has been already

**Comment by Ste74** [comment]
So is ok .. so yes i had the rm command on the script 😉
